version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.01.2
    steps:
      - checkout
      - run:
          name: Zainstaluj zaleznosci
          command: make deps
      - run:
          name: Sprawdz styl (Linter)
          command: make lint
      - run:
          name: Uruchom testy
          command: make test
      - run:
          name: Buduj obraz Docker
          command: make docker_build
          
workflows:
  basic:
    jobs:
      - build-and-test
