version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Zainstaluj zaleznosci
          command: make deps
      - run:
          name: Sprawdz styl (Linter)
          command: make lint
      - run:
          name: Uruchom testy
          command: make test

workflows:
  basic:
    jobs:
      - build-and-test
